config/routes.rb
Rails.application.routes.draw do
  root 'tracks#index'

  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  resources :tracks, only: [:index, :show, :new, :create] do
    resources :moments, only: [:new, :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moment.rb
class Moment < ApplicationRecord
  has_rich_text :content

  # Associations
  belongs_to :track
  has_one_attached :feature_image

  # Validations
  validates_presence_of :title, :content, :track, :original_date
  validates :feature_image, content_type: ["image/png", "image/jpg", "image/jpeg"]

  # Callbacks
  before_validation :set_original_date

  private

  def set_original_date
    self.original_date ||= Time.zone.now
  end
end

app/models/track.rb
class Track < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :moments, -> { order(original_date: :desc) }

  # Validations
  validates_presence_of :user, :name
  validates_uniqueness_of :name,
    scope: :user_id,
    case_sensitive: false
end

app/models/user.rb
class User < ApplicationRecord
  # Associations
  has_many :tracks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    tracks_path
  end

  def not_found
    raise ActionController::RoutingError.new("Not Found")
  end
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track
  before_action :set_moment, only: [:edit, :update]

  def new
    @moment = Moment.new
    @errors = []
  end

  def create
    result = Moments::Creator.new(track: @track, params: moment_params).call

    if result.success?
      flash[:success] = "New moment successfully created!"
      redirect_to track_path(@track)
    else
      @moment = result.data
      @errors = result.errors
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    result = Moments::Updater.new(moment: @moment, params: moment_params).call

    if result.success?
      flash[:success] = "Moment successfully updated!"
      redirect_to track_path(@track)
    else
      @moment = result.data
      @errors = result.errors
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_track
    @track = Tracks::Finder.track_for_user(current_user, params[:track_id]) || not_found
  end

  def set_moment
    @moment = Moments::Finder.moments_for_track(@track).find(params[:id])
  end

  def moment_params
    params.require(:moment).permit(
      :content,
      :original_date,
      :title,
      :feature_image,
    )
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_track, only: [:show]

  def index
    @tracks = Tracks::Finder.tracks_for_user(current_user)
  end

  def show
    @moments = Moments::Finder.moments_for_track(@track)
  end

  def new
    @track = Track.new
    @errors = []
  end

  def create
    result = Tracks::Creator.new(user: current_user, params: track_params).call

    if result.success?
      flash[:success] = "New track successfully created!"
      redirect_to tracks_path
    else
      @track = result.data
      @errors = result.errors
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_track
    @track = Tracks::Finder.track_for_user(current_user, params[:id])

    unless @track.present?
      render json: { errors: "Could not find the specified track" }, status: :not_found
    end
  end

  def track_params
    params.require(:track).permit(
      :name,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def react_component(component, props = {}, tag = 'div')
    id = "react-#{component.underscore.dasherize}"
    data = { camelized_props: ReactHelper.camelize_props(props.as_json) }

    content_tag tag, id: id, data: data do
      javascript_pack_tag component
    end
  end

  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info",
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/react_helper.rb
# This is taken from react-rails/lib/react.rb
# If we ever start using react-rails, this should go away,
# we shouldn't duplicate the effort at that point.

module ReactHelper
  # Recursively camelize `props`, returning a new Hash
  # @param props [Object] If it's a Hash or Array, it will be recursed. Otherwise it will be returned.
  # @return [Hash] a new hash whose keys are camelized strings
  def self.camelize_props(props)
    case props
    when Hash
      props.each_with_object({}) do |(key, value), new_props|
        new_key = key.to_s.camelize(:lower)
        new_value = camelize_props(value)
        new_props[new_key] = new_value
      end
    when Array
      props.map { |item| camelize_props(item) }
    else
      props
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_nav.html.erb
<nav
  class="relative w-full flex flex-wrap items-center justify-between py-3 shadow-sm navbar navbar-expand-lg navbar-light"
>
  <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
    <button
      class="navbar-toggler text-gray-200 border-0 hover:shadow-none hover:no-underline py-2 px-2.5 bg-transparent focus:outline-none focus:ring-0 focus:shadow-none focus:no-underline"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent1"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <svg
        aria-hidden="true"
        focusable="false"
        data-prefix="fas"
        data-icon="bars"
        class="w-6"
        role="img"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 448 512"
      >
        <path
          fill="currentColor"
          d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"
        ></path>
      </svg>
    </button>
    <div class="collapse navbar-collapse flex-grow items-center" id="navbarSupportedContent1">
      <%= link_to "MMNT", root_path, class: "navbar-brand" %>
      <!-- Left links -->
      <ul class="navbar-nav flex flex-col pl-0 list-style-none mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item p-2">
            <%= link_to "Tracks", tracks_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="flex items-center relative space-x-2">
      <% if user_signed_in? %>
        <%= link_to "Logout", logout_path, class: "nav-link" %>
      <% else %>
        <%= link_to "Login", login_path, class: "nav-link" %>
        <%= link_to "Signup", signup_path, class: "nav-link" %>
      <% end %>
    </div>
    <!-- Right elements -->
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mmnt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://kit.fontawesome.com/bd54375e54.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <div class="p-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/moments/_form.html.erb
<%= form_with(
  url: action == "create" ? track_moments_path(@track) : track_moment_path(@track, @moment),
  method: action == "create" ? :post : :patch,
  scope: :moment
) do |form| %>
  <div class="w-full lg:w-1/2 flex flex-col space-y-4">
    <% if @errors&.any? %>
      <div class="alert alert-danger" role="alert">
        <%= pluralize(@errors.count, "error") %> prohibited this record from being saved:
        <ul>
          <% @errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.file_field :feature_image %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-input" %>
    </div>

    <div>
      <%= form.label :content, "Describe your moment..." %>
      <%= form.rich_text_area :content, class: "form-input" %>
    </div>

    <div>
      <%= form.label :original_date, "When did it happen?" %>
      <%= form.date_field :original_date, class: "form-input" %>
    </div>

    <%= form.submit "#{action == "create" ? "Create" : "Update"} Moment", class: "button-primary" %>
  </div>
<% end %>

app/views/moments/edit.html.erb
<%= render "form", action: "update" %>

app/views/moments/new.html.erb
<%= render "form", action: "create" %>

app/views/tracks/index.html.erb
<div class="row">
  <div class="col">
    <%= link_to "New Track", new_track_path, class: "button-primary float-right" %>
  </div>
</div>

<div class="grid grid-cols-1 gap-10 lg:grid-cols-3 mt-[50px]">
  <% @tracks.each do |track| %>
    <%= link_to track_path(track) do %>
      <div class="flex shadow-md h-48 rounded-l-md">
        <div class="flex-none w-32 rounded-l-md gradient-bg text-7xl text-white text-center leading-[192px]">
          <%= track.name[0].upcase %>
        </div>
        <div class="flex-auto p-6">
          <div class="text-xl pb-2 border-b border-slate-100">
            <%= track.name %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/tracks/new.html.erb
<%= form_with(model: @track) do |form| %>
  <div class="w-full lg:w-1/2 flex flex-col space-y-4">
    <% if @errors.any? %>
      <div class="alert alert-danger" role="alert">
        <%= pluralize(@errors.count, "error") %> prohibited this record from being saved:
        <ul>
          <% @errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <%= form.submit "Create Track", class: "button-primary" %>
  </div>
<% end %>

app/views/tracks/show.html.erb
<div class="row">
  <div class="col">
    <%= link_to "New Moment", new_track_moment_path(@track), class: "button-primary float-right" %>
  </div>
</div>

<h1 class="text-3xl"><%= @track.name %></h1>

<div class="grid grid-cols-1 gap-10 lg:grid-cols-2 mt-[50px]">
  <% @track.moments.each do |moment| %>
    <div class="flex flex-col shadow-lg h-full min-h-48 rounded-lg lg:flex-row">
      <div class="flex-none w-full max-h-96 rounded-l-lg gradient-bg text-7xl text-white text-center leading-[192px] lg:w-48 lg:max-h-full lg:rounded-none lg:rounded-l-lg">
        <% if moment.feature_image.present? %>
          <%= image_tag(
            url_for(moment.feature_image.variant(resize_to_limit: [600, 600]).processed),
            alt: moment.title,
            class: "w-full h-full rounded-t-lg object-cover lg:rounded-none lg:rounded-l-lg"
          ) %>
        <% end %>
      </div>
      <div class="flex-auto p-6">
        <div class="flex text-xl pb-2 mb-5 border-b border-slate-100">
          <h4>
            <%= moment.title %> |
            <span class="text-sm text-slate-400">
              <%= moment.original_date.strftime("%m/%d/%Y") %>
            </span>
          </h4>
          <%= link_to "edit", edit_track_moment_path(@track, moment), class: "ml-auto text-xs text-slate-300 align-middle !leading-loose" %>
        </div>
        <p><%= moment.content %></p>
      </div>
    </div>
  <% end %>
</div>

<% if @track.moments.empty? %>
  Track your first moment!
<% end %>